name: Build Memora frame App for Linux ARM64

on:
  push:
    branches:
      - master

jobs:
  build-linux-arm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x  

  
      - name: Update version
        run: |
          NEW_VERSION="0.0.$(git rev-list --count HEAD)"

      # - name: Install dependencies
        # run: npm run lint
      - name: Push Version Tags
        uses: ovsds/push-version-tags-action@v1
        with:
          version: ${{ NEW_VERSION }}

      # - name: Push Git Tag
      #   run: |
      #     NEW_VERSION="0.0.$(git rev-list --count HEAD)"
      #     npm version $NEW_VERSION --no-git-tag-version
      #     git config user.name "GitHub Actions"
      #     git config user.email "github-actions@users.noreply.github.com"
      #     git tag $NEW_VERSION
      #     git push origin $NEW_VERSION